ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StudyRoom" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Message" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_JoinedRooms" ENABLE ROW LEVEL SECURITY;
